name: Invoke Lambda (Manual)

on:
  workflow_dispatch:

jobs:
  invoke:
    name: Invoke Lambda to Initialize DB
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/lambda/sql_initializer

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-northeast-2

      - name: Invoke Lambda to initialize DB
        run: |
          set -e
          echo "Invoking Lambda rds-sql-initializer..."
          aws lambda invoke \
            --function-name rds-sql-initializer \
            --payload '{}' \
            --region ap-northeast-2 \
            init-db-response.json
          echo "Lambda response:"
          cat init-db-response.json
